language: node_js

node_js:
  - "10.14.1"

sudo: true

env:
  - CXX=g++-4.8 NODE_ENV=testing
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - postgresql
  - docker

before_install:
  - wget -q0- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

before_script:
  - psql -c "CREATE DATABASE authserver;" -U postgres
  - npm run migrations-test

script:
  - docker build -t chotuveg3/auth-server-develop .
  - docker tag chotuveg3/auth-server-develop registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: script
  script:
    docker push chotuveg3/auth-server-develop;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  on:
    branch: docker
