language: node_js

node_js:
  - "10.14.1"

sudo: true

env:
  - CXX=g++-4.8 NODE_ENV=testing
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - postgresql
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

before_script:
  - psql -c "CREATE DATABASE authserver;" -U postgres
  - npm run migrations-test

script:
  - docker build -t chotuveg3/auth-server .

deploy:
  provider: script
  script: docker push chotuveg3/auth-server;
  branch: docker
